name: Get PR info action
description: Get PR info action
author: stevei5mc

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-pull-request
  color: red

# Define your inputs here.
inputs:
  repoName:
    description: Repo name
    required: true
    default: '${{ github.repository }}'
  prId:
    description: PR ID
    required: true
    default: '${{ github.event.pull_request.number }}'

# Define your outputs here.
# outputs:
#   time:
#     description: Your output description here 

runs:
  using: node20
  main: dist/index.js
