name: Get PR info action
description: Get PR info action
author: stevei5mc

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-pull-request
  color: blue

# Define your inputs here.
inputs:
  repoName:
    description: Repo name
    required: true
    default: '${{ github.repository }}'
  prId:
    description: PR ID
    required: true
    default: '${{ github.event.pull_request.number }}'

# Define your outputs here.
outputs:
  apiUrl:
    description: Pull request api url
  htmlUrl:
    description: Pull request url
  prState:
    description: Pull request state
  prLockedState:
    description: Pull request locked state
  prDraftState:
    description: Pull request draft state
  requestUser:
    description: Pull request initiate user name
  createdAt:
    description: Pull request state
  updatedAt:
    description: Pull request locked state
  closedAt:
    description: Pull request draft state
  commits:
    description: Pull request commits count
  additions:
    description: Pull request additions line
  deletions:
    description: Pull request deletions line
  changedFiles:
    description: Pull request changed files
  headSha:
    description: Pull request head sha
  headRef:
    description: Pull request head sha
  headLabel:
    description: Pull request head label
  headUserName:
    description: Pull request head user name
  headFullName:
    description: Pull request head full name
  headRepoUrl:
    description: Pull request head repo url
  baseSha:
    description: Pull request base sha
  baseRef:
    description: Pull request base sha
  baseLabel:
    description: Pull request base label
  baseUserName:
    description: Pull request base user name
  baseFullName:
    description: Pull request base full name
  baseRepoUrl:
    description: Pull request base repo url
  prMergedState:
    description: Pull request merged state
  prMergedBy:
    description: Pull request merged state

runs:
  using: node20
  main: dist/index.js
