name: Get PR info action
description: Get PR info action
author: stevei5mc

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-pull-request
  color: blue

# Define your inputs here.
inputs:
  repoName:
    description: Repo name
    required: true
    default: '${{ github.repository }}'
  prId:
    description: PR ID
    required: true
    default: '${{ github.event.pull_request.number }}'

# Define your outputs here.
outputs:
  apiUrl:
    description: Your output description here
  htmlUrl:
    description: Your output description here
  commits:
    description: Your output description here
  additions:
    description: Your output description here
  deletions:
    description: Your output description here
  changedFiles:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
