name: Get PR info action
description: Get PR info action
author: stevei5mc

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-pull-request
  color: blue

# Define your inputs here.
inputs:
  repoName:
    description: Repo name
    required: true
    default: '${{ github.repository }}'
  prId:
    description: PR ID
    required: true
    default: '${{ github.event.pull_request.number }}'

# Define your outputs here.
outputs:
  apiUrl:
    description: Request api url
  htmlUrl:
    description: Pull request url
  commits:
    description: Pull request commits count
  additions:
    description: Pull request additions line
  deletions:
    description: Pull request deletions line
  changedFiles:
    description: Pull request changed files
  headSha:
    description: Pull request head sha
  headFullName:
    description: Pull request head full name
  baseSha:
    description: Pull request base sha
  baseFullName:
    description: Pull request base full name
runs:
  using: node20
  main: dist/index.js
